// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Character struct {
	Name        string  `json:"name"`
	Player      *Player `json:"player"`
	Description *string `json:"description"`
}

type CharacterInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

type LoginInput struct {
	Playername string `json:"playername"`
	Password   string `json:"password"`
}

type Player struct {
	Name string `json:"name"`
}

type PlayerInput struct {
	Name string `json:"name"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}
